// mobile/app/medico.tsx
/**
 * Panel medico mobile — Registro de dosis al momento.
 *
 * Flujo:
 *  1) Medico autenticado (rol = 'medico' validado en useEffect).
 *  2) Escanea QR personal del paciente con expo-camera (BarCodeScanner).
 *  3) Endpoint /certificados/verificar/{token} valida y devuelve usuario + resumen.
 *  4) Selecciona vacuna, dosis, lugar y lote.
 *  5) POST /certificados/aplicar-por-token con `actor_curp` = CURP del medico.
 *
 * La fecha y hora se capturan automaticamente al guardar (registrado_en).
 */
import { useCallback, useEffect, useState } from 'react'
import {
  View,
  ScrollView,
  Pressable,
  StyleSheet,
  ActivityIndicator,
} from 'react-native'
import { router } from 'expo-router'
import { SafeAreaView } from 'react-native-safe-area-context'
import { CameraView, useCameraPermissions } from 'expo-camera'

import { Text } from '@/components/ui/Text'
import { Field } from '@/components/ui/Field'
import { Button } from '@/components/ui/Button'
import { Modal } from '@/components/ui/Modal'
import { ChipSelector } from '@/components/ui/ChipSelector'
import { useToast } from '@/components/ui/Toast'

import {
  certificadosApi,
  type UsuarioVerificado,
  type ResumenVacuna,
} from '@/api/certificados'
import { adminApi } from '@/api/admin'
import type { CatalogoVacunaRow } from '@/types/admin'

import { sessionStore } from '@/hooks/useSession'
import { normalizarCurp, esCurpValida } from '@/utils/curp'
import { colors, spacing } from '@/theme'

type Fase = 'scan' | 'manual' | 'paciente' | 'registrar' | 'exito'

const LUGARES_APLICACION = [
  'UMF',
  'Hospital',
  'Centro de salud',
  'Campania escolar',
  'Brigada movil',
  'Domiciliaria',
  'Modulo de vacunacion',
] as const

export default function MedicoScreen() {
  const toast = useToast()
  const [authorized, setAuthorized] = useState<boolean | null>(null)
  const [nombreMedico, setNombreMedico] = useState('')
  const [curpMedico, setCurpMedico] = useState('')

  const [permission, requestPermission] = useCameraPermissions()

  const [fase, setFase] = useState<Fase>('scan')
  const [error, setError] = useState('')
  const [cargando, setCargando] = useState(false)
  const [scanning, setScanning] = useState(true)

  const [tokenPaciente, setTokenPaciente] = useState('')
  const [pacienteCurp, setPacienteCurp] = useState('')
  const [paciente, setPaciente] = useState<UsuarioVerificado | null>(null)
  const [resumen, setResumen] = useState<ResumenVacuna[]>([])

  const [catalogo, setCatalogo] = useState<CatalogoVacunaRow[]>([])

  const [form, setForm] = useState({
    vacuna_id: 0,
    numero_dosis: 1,
    lugar_aplicacion: '',
    lote: '',
  })

  const [ultimaDosis, setUltimaDosis] = useState<{ vacuna: string; numero: number } | null>(null)

  useEffect(() => {
    ;(async () => {
      const medico = await sessionStore.isMedico()
      const auth = await sessionStore.isAuthenticated()
      if (!medico) {
        const rol = await sessionStore.getRol()
        if (rol === 'admin') {
          router.replace('/admin')
        } else {
          router.replace('/inicio')
        }
        return
      }
      if (!auth) {
        router.replace('/login')
        return
      }
      const n = await sessionStore.getUserName()
      const c = await sessionStore.getCurp()
      if (n) setNombreMedico(n)
      if (c) setCurpMedico(c)
      setAuthorized(true)
    })()
  }, [])

  useEffect(() => {
    adminApi.listarCatalogo().then(setCatalogo).catch(() => {})
  }, [])

  const procesarToken = useCallback(async (token: string) => {
    if (cargando) return
    setCargando(true)
    setError('')
    try {
      const data = await certificadosApi.verificarToken(token)
      if (!data.valido) {
        throw new Error('Token invalido o expirado.')
      }
      setTokenPaciente(token)
      setPacienteCurp(data.usuario.curp)
      setPaciente(data.usuario)
      setResumen(data.resumen || [])
      setScanning(false)
      setFase('paciente')
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'No se pudo verificar el codigo.'
      setError(msg)
      setScanning(true) // permitir reintento
    } finally {
      setCargando(false)
    }
  }, [cargando])

  function onScan({ data }: { data: string }) {
    if (!scanning || cargando) return
    setScanning(false)
    // Algunos QR vienen como URL; extraemos el token si aplica.
    const token = data.includes('/verificar/')
      ? (data.split('/verificar/').pop() || '').replace(/[/?#].*$/, '')
      : data.trim()
    if (!token) {
      setScanning(true)
      return
    }
    procesarToken(token)
  }

  async function buscarPorCurp() {
    const curp = normalizarCurp(pacienteCurp)
    if (!esCurpValida(curp)) {
      setError('La CURP debe tener 18 caracteres validos.')
      return
    }
    setCargando(true)
    setError('')
    try {
      const r = await certificadosApi.obtenerTokenQr(curp)
      await procesarToken(r.token)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'No se encontro el paciente.')
    } finally {
      setCargando(false)
    }
  }

  function abrirRegistro(vacunaId: number) {
    const v = catalogo.find(c => c.id === vacunaId)
    const r = resumen.find(x => x.vacuna_id === vacunaId)
    setForm({
      vacuna_id: vacunaId,
      numero_dosis: r
        ? Math.min((r.dosis_aplicadas || 0) + 1, v?.dosis_total || 1)
        : 1,
      lugar_aplicacion: '',
      lote: '',
    })
    setError('')
    setFase('registrar')
  }

  async function aplicarDosis() {
    setError('')
    if (!form.vacuna_id) {
      setError('Selecciona una vacuna.')
      return
    }
    if (form.numero_dosis < 1) {
      setError('El numero de dosis debe ser al menos 1.')
      return
    }
    setCargando(true)
    try {
      const hoy = new Date().toISOString().slice(0, 10)
      await certificadosApi.aplicarPorToken({
        token: tokenPaciente,
        vacuna_id: form.vacuna_id,
        numero_dosis: form.numero_dosis,
        fecha_aplicacion: hoy,
        lugar_aplicacion: form.lugar_aplicacion.trim() || undefined,
        lote: form.lote.trim() || undefined,
        actor_curp: curpMedico,
      })
      const vac = catalogo.find(c => c.id === form.vacuna_id)
      setUltimaDosis({
        vacuna: vac?.nombre || 'Vacuna',
        numero: form.numero_dosis,
      })
      toast.success('Dosis registrada en la cartilla del paciente.', 'OK')
      setFase('exito')
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'No se pudo registrar la dosis.'
      setError(msg)
      toast.error(msg, 'Error')
    } finally {
      setCargando(false)
    }
  }

  function nuevoPaciente() {
    setTokenPaciente('')
    setPacienteCurp('')
    setPaciente(null)
    setResumen([])
    setUltimaDosis(null)
    setError('')
    setScanning(true)
    setFase('scan')
  }

  function volverAPaciente() {
    setFase('paciente')
    setError('')
  }

  async function handleLogout() {
    await sessionStore.logout()
    router.replace('/login')
  }

  if (authorized !== true) {
    return <SafeAreaView style={{ flex: 1, backgroundColor: colors.paper }} />
  }

  const sumario = resumen.length
    ? {
        completas: resumen.filter(r => r.completa).length,
        pendientes: resumen.filter(r => !r.completa).length,
        total: resumen.length,
      }
    : null

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.paper }}>
      <ScrollView
        contentContainerStyle={{ padding: spacing.xl, paddingBottom: spacing.xxxl, gap: spacing.lg }}
      >
        {/* Header */}
        <View
          style={{
            borderBottomWidth: 2,
            borderBottomColor: colors.ink,
            paddingBottom: spacing.lg,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
            gap: spacing.md,
          }}
        >
          <View style={{ flex: 1 }}>
            <Text variant="eyebrow" color="muted">Panel medico</Text>
            <Text variant="display" style={{ marginTop: spacing.sm, fontSize: 32, lineHeight: 36 }}>
              Registro de{'\n'}
              <Text variant="display" italic style={{ fontSize: 32, lineHeight: 36 }}>
                dosis.
              </Text>
            </Text>
            {nombreMedico ? (
              <Text variant="small" color="muted" style={{ marginTop: spacing.sm }}>
                {nombreMedico}
              </Text>
            ) : null}
          </View>
          <Pressable
            onPress={handleLogout}
            hitSlop={12}
            accessibilityRole="button"
            accessibilityLabel="Cerrar sesion"
          >
            <Text variant="eyebrow" color="muted">SALIR ↗</Text>
          </Pressable>
        </View>

        {/* FASE: SCAN */}
        {fase === 'scan' ? (
          <View style={{ gap: spacing.lg }}>
            <View>
              <Text variant="eyebrow" color="muted">Paso 1</Text>
              <Text variant="h1" style={{ marginTop: spacing.xs }}>
                Escanea el <Text variant="h1" italic>QR del paciente.</Text>
              </Text>
              <Text variant="small" color="muted" style={{ marginTop: spacing.sm }}>
                Pide al ciudadano que abra su cartilla y muestre su codigo QR personal.
              </Text>
            </View>

            <View style={styles.scannerFrame}>
              {!permission ? (
                <View style={styles.scannerFallback}>
                  <ActivityIndicator color={colors.paper} />
                </View>
              ) : !permission.granted ? (
                <View style={styles.scannerFallback}>
                  <Text variant="eyebrow" color="paper" style={{ opacity: 0.7 }}>Sin permiso</Text>
                  <Text variant="small" color="paper" style={{ marginTop: spacing.sm, opacity: 0.85, textAlign: 'center' }}>
                    Necesitamos acceso a la camara para leer el QR del paciente.
                  </Text>
                  <View style={{ marginTop: spacing.md, alignSelf: 'center' }}>
                    <Button label="Dar permiso" variant="ghost" onPress={requestPermission} />
                  </View>
                </View>
              ) : (
                <CameraView
                  style={StyleSheet.absoluteFill}
                  barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
                  onBarcodeScanned={scanning ? onScan : undefined}
                  facing="back"
                />
              )}
            </View>

            <Pressable
              onPress={() => { setFase('manual'); setError('') }}
              accessibilityRole="button"
              style={{ alignSelf: 'flex-start', paddingVertical: spacing.xs }}
            >
              <Text variant="eyebrow">Buscar por CURP manualmente →</Text>
            </Pressable>

            {error ? (
              <View
                style={{
                  borderLeftWidth: 2,
                  borderLeftColor: colors.wine,
                  paddingLeft: spacing.md,
                  paddingVertical: spacing.sm,
                }}
              >
                <Text variant="small" color="wine">{error}</Text>
              </View>
            ) : null}
          </View>
        ) : null}

        {/* FASE: MANUAL */}
        {fase === 'manual' ? (
          <View style={{ gap: spacing.lg }}>
            <View>
              <Text variant="eyebrow" color="muted">Busqueda manual</Text>
              <Text variant="h1" style={{ marginTop: spacing.xs }}>CURP del paciente</Text>
              <Text variant="small" color="muted" style={{ marginTop: spacing.sm }}>
                Si el QR no esta disponible, ingresa la CURP de 18 caracteres.
              </Text>
            </View>

            <Field
              label="CURP"
              value={pacienteCurp}
              onChangeText={(t) => setPacienteCurp(normalizarCurp(t))}
              placeholder="XXXX000000XXXXXXXX"
              autoCapitalize="characters"
              autoCorrect={false}
              maxLength={18}
              mono
              returnKeyType="search"
              onSubmitEditing={buscarPorCurp}
            />

            {error ? (
              <View
                style={{
                  borderLeftWidth: 2,
                  borderLeftColor: colors.wine,
                  paddingLeft: spacing.md,
                  paddingVertical: spacing.sm,
                }}
              >
                <Text variant="small" color="wine">{error}</Text>
              </View>
            ) : null}

            <View style={{ flexDirection: 'row', gap: spacing.sm }}>
              <View style={{ flex: 1 }}>
                <Button
                  label={cargando ? 'Buscando...' : 'Continuar'}
                  loading={cargando}
                  arrow={!cargando}
                  onPress={buscarPorCurp}
                />
              </View>
              <Button
                label="Volver al QR"
                variant="ghost"
                onPress={() => { setFase('scan'); setError(''); setScanning(true) }}
              />
            </View>
          </View>
        ) : null}

        {/* FASE: PACIENTE */}
        {fase === 'paciente' && paciente ? (
          <View style={{ gap: spacing.lg }}>
            <View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: spacing.md }}>
                <View style={{ flex: 1 }}>
                  <Text variant="eyebrow" color="muted">Paciente identificado</Text>
                  <Text variant="h1" style={{ marginTop: spacing.xs }}>
                    {paciente.nombre} {paciente.apellido_paterno}
                    {paciente.apellido_materno ? ` ${paciente.apellido_materno}` : ''}
                  </Text>
                  <Text variant="mono" color="muted" style={{ marginTop: spacing.xs, fontSize: 11, letterSpacing: 1.2 }}>
                    {paciente.curp}
                  </Text>
                </View>
                <Pressable onPress={nuevoPaciente} hitSlop={8} accessibilityRole="button">
                  <Text variant="eyebrow" color="muted">CAMBIAR ↗</Text>
                </Pressable>
              </View>
            </View>

            {sumario ? (
              <View style={{ flexDirection: 'row', gap: spacing.xl }}>
                <Stat n={sumario.completas} label="Completas" />
                <Stat
                  n={sumario.pendientes}
                  label="Pendientes"
                  highlight={sumario.pendientes > 0}
                />
                <Stat n={sumario.total} label="Vacunas" />
              </View>
            ) : null}

            <View>
              <View style={{ borderBottomWidth: 1, borderBottomColor: colors.ink, paddingBottom: spacing.sm, marginBottom: spacing.md, flexDirection: 'row', justifyContent: 'space-between' }}>
                <Text variant="h2">Aplicar dosis</Text>
                <Text variant="eyebrow" color="muted">Elige la vacuna</Text>
              </View>

              {resumen.length === 0 ? (
                <View style={{ paddingVertical: spacing.xl, alignItems: 'center' }}>
                  <Text variant="h2" italic color="muted" style={{ textAlign: 'center', fontSize: 18 }}>
                    Sin vacunas en su esquema todavia.
                  </Text>
                  {catalogo.length ? (
                    <View style={{ marginTop: spacing.md }}>
                      <Button
                        label="Registrar primera dosis"
                        onPress={() => abrirRegistro(catalogo[0]!.id)}
                        arrow
                      />
                    </View>
                  ) : null}
                </View>
              ) : (
                resumen.map((r, i) => {
                  const dosisProx = Math.min(r.dosis_aplicadas + 1, r.dosis_total)
                  return (
                    <Pressable
                      key={r.vacuna_id}
                      onPress={() => !r.completa && abrirRegistro(r.vacuna_id)}
                      disabled={r.completa}
                      style={({ pressed }) => [
                        {
                          paddingVertical: spacing.md,
                          borderBottomWidth: i < resumen.length - 1 ? 1 : 0,
                          borderBottomColor: colors.borderSoft,
                          flexDirection: 'row',
                          alignItems: 'center',
                          justifyContent: 'space-between',
                          gap: spacing.md,
                          opacity: r.completa ? 0.5 : pressed ? 0.7 : 1,
                        },
                      ]}
                    >
                      <View style={{ flex: 1, minWidth: 0 }}>
                        <Text variant="body" bold numberOfLines={1}>{r.nombre}</Text>
                        <Text variant="small" color="muted" style={{ marginTop: 2 }}>
                          {r.dosis_aplicadas} de {r.dosis_total} dosis
                        </Text>
                      </View>
                      {r.completa ? (
                        <Text variant="mono" color="moss" style={{ fontSize: 10, letterSpacing: 1 }}>
                          COMPLETA
                        </Text>
                      ) : (
                        <Text variant="mono" color="moss" style={{ fontSize: 12, letterSpacing: 0.5 }}>
                          + DOSIS {dosisProx} →
                        </Text>
                      )}
                    </Pressable>
                  )
                })
              )}
            </View>

            {error ? (
              <View
                style={{
                  borderLeftWidth: 2,
                  borderLeftColor: colors.wine,
                  paddingLeft: spacing.md,
                  paddingVertical: spacing.sm,
                }}
              >
                <Text variant="small" color="wine">{error}</Text>
              </View>
            ) : null}
          </View>
        ) : null}

        {/* FASE: EXITO */}
        {fase === 'exito' && paciente && ultimaDosis ? (
          <View
            style={{
              borderLeftWidth: 4,
              borderLeftColor: colors.moss,
              paddingLeft: spacing.lg,
              paddingVertical: spacing.md,
              gap: spacing.sm,
            }}
          >
            <Text variant="eyebrow" color="moss">Dosis registrada</Text>
            <Text variant="h1">
              {ultimaDosis.vacuna}{' '}
              <Text variant="h1" italic color="muted">dosis {ultimaDosis.numero}.</Text>
            </Text>
            <Text variant="small" color="muted">
              Quedo registrada en la cartilla de{' '}
              <Text bold>{paciente.nombre} {paciente.apellido_paterno}</Text>
              {' '}con fecha y hora de hoy.
            </Text>

            <View style={{ flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md, flexWrap: 'wrap' }}>
              <View style={{ flex: 1, minWidth: 200 }}>
                <Button label="Otra dosis al mismo" onPress={volverAPaciente} arrow />
              </View>
              <Button label="Nuevo paciente" variant="ghost" onPress={nuevoPaciente} />
            </View>
          </View>
        ) : null}
      </ScrollView>

      {/* Modal de registro (overlay) */}
      <Modal
        visible={fase === 'registrar'}
        onClose={volverAPaciente}
        eyebrow="Registrar dosis"
        title={catalogo.find(c => c.id === form.vacuna_id)?.nombre || ''}
      >
        {paciente ? (
          <Text variant="small" color="muted">
            Paciente: <Text variant="mono" color="muted" style={{ fontSize: 11, letterSpacing: 1 }}>{paciente.curp}</Text>{'\n'}
            {paciente.nombre} {paciente.apellido_paterno}
          </Text>
        ) : null}

        <Field
          label="Numero de dosis"
          value={String(form.numero_dosis)}
          onChangeText={(t) =>
            setForm({
              ...form,
              numero_dosis: Math.max(1, parseInt(t.replace(/[^0-9]/g, '') || '1', 10)),
            })
          }
          keyboardType="number-pad"
        />

        <ChipSelector
          label="Lugar de aplicacion"
          options={LUGARES_APLICACION}
          value={form.lugar_aplicacion}
          onChange={(v) => setForm({ ...form, lugar_aplicacion: v })}
          allowCustom
          customLabel="Otro..."
          customPlaceholder="Ej. UMF #43, campania..."
        />

        <Field
          label="Lote (opcional)"
          value={form.lote}
          onChangeText={(t) => setForm({ ...form, lote: t })}
          placeholder="LOT-XXX-000"
          maxLength={60}
          mono
        />

        <View
          style={{
            borderTopWidth: 1,
            borderTopColor: colors.border,
            paddingTop: spacing.sm,
            gap: spacing.xs / 2,
          }}
        >
          <Text variant="mono" color="muted" style={{ fontSize: 10, letterSpacing: 1.1 }}>
            FECHA · {new Date().toLocaleDateString('es-MX')}
          </Text>
          <Text variant="mono" color="muted" style={{ fontSize: 10, letterSpacing: 1.1 }}>
            HORA · {new Date().toLocaleTimeString('es-MX')}
          </Text>
          <Text variant="mono" color="muted" style={{ fontSize: 10, letterSpacing: 1.1 }}>
            FIRMADO POR · {curpMedico}
          </Text>
        </View>

        {error ? (
          <View
            style={{
              borderLeftWidth: 2,
              borderLeftColor: colors.wine,
              paddingLeft: spacing.md,
              paddingVertical: spacing.sm,
            }}
          >
            <Text variant="small" color="wine">{error}</Text>
          </View>
        ) : null}

        <View style={{ flexDirection: 'row', gap: spacing.sm }}>
          <View style={{ flex: 1 }}>
            <Button
              label={cargando ? 'Registrando...' : 'Aplicar dosis'}
              loading={cargando}
              onPress={aplicarDosis}
              arrow={!cargando}
            />
          </View>
          <Button label="Cancelar" variant="ghost" onPress={volverAPaciente} />
        </View>
      </Modal>
    </SafeAreaView>
  )
}

function Stat({
  n,
  label,
  highlight,
}: {
  n: number
  label: string
  highlight?: boolean
}) {
  return (
    <View style={{ minWidth: 60 }}>
      <Text
        variant="display"
        color={highlight ? 'wine' : 'ink'}
        style={{ fontSize: 32, lineHeight: 34 }}
      >
        {n}
      </Text>
      <Text variant="eyebrow" color="muted" style={{ marginTop: 2 }}>{label}</Text>
    </View>
  )
}

const styles = StyleSheet.create({
  scannerFrame: {
    borderWidth: 2,
    borderColor: colors.ink,
    aspectRatio: 4 / 3,
    overflow: 'hidden',
    backgroundColor: colors.mossDark,
    position: 'relative',
  },
  scannerFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
})

// frontend/app/pages/medico.vue
<script setup lang="ts">
/**
 * Panel medico — Registro de dosis al momento.
 *
 * Flujo:
 *  1) Medico autenticado (middleware 'medico' obliga rol + password).
 *  2) Escanea QR personal del paciente (genera un token corto en /certificados/{curp}/qr-token).
 *  3) Endpoint /certificados/verificar/{token} valida + devuelve usuario + resumen.
 *  4) Medico selecciona vacuna, numero de dosis, lugar y lote.
 *  5) POST /certificados/aplicar-por-token registra la dosis con:
 *     - fecha_aplicacion = hoy (auto)
 *     - modificado_por   = CURP del medico (actor_curp)
 *     - registrado_en    = NOW() automatico
 */
import { QrcodeStream } from 'vue-qrcode-reader'

definePageMeta({ middleware: 'medico' })
useHead({ title: 'Panel medico' })

const router = useRouter()
const api = useApi()
const session = useSession()

const nombreMedico = ref('')
const curpMedico = ref('')

type UsuarioVerificado = {
  curp: string
  nombre: string
  apellido_paterno: string
  apellido_materno: string | null
  fecha_nacimiento: string | null
  sexo: string | null
  unidad_nombre: string | null
}

type ResumenVacuna = {
  vacuna_id: number
  nombre: string
  dosis_total: number
  dosis_aplicadas: number
  completa: boolean
}

type CatalogoItem = {
  id: number
  nombre: string
  enfermedad: string
  dosis_total: number
  dosis_descripcion: string | null
}

const fase = ref<'scan' | 'manual' | 'paciente' | 'registrar' | 'exito'>('scan')
const error = ref('')
const cargando = ref(false)

const tokenPaciente = ref('')
const pacienteCurp = ref('')
const paciente = ref<UsuarioVerificado | null>(null)
const resumen = ref<ResumenVacuna[]>([])

const catalogo = ref<CatalogoItem[]>([])

const form = reactive({
  vacuna_id: 0,
  numero_dosis: 1,
  lugar_aplicacion: '',
  lote: '',
})

const ultimaDosisAplicada = ref<{ vacuna: string; numero: number } | null>(null)

const cameraSoportada = ref(true)
const cameraEnabled = ref(true)

onMounted(async () => {
  const n = session.getUserName()
  const c = session.getCurp()
  if (n) nombreMedico.value = n
  if (c) curpMedico.value = c

  try {
    catalogo.value = await api.getCatalogo() as CatalogoItem[]
  } catch (e) {
    console.error(e)
  }
})

function logout() {
  session.logout()
  router.replace('/login')
}

async function onScan(detected: { rawValue?: string }[]) {
  if (!detected.length) return
  const raw = detected[0]?.rawValue || ''
  // Algunos QR vienen como URL completa; extraemos el token si aplica.
  const token = raw.includes('/verificar/')
    ? (raw.split('/verificar/').pop() || '').replace(/[/?#].*$/, '')
    : raw.trim()

  if (!token) return
  await procesarToken(token)
}

function onCameraError(err: Error) {
  cameraSoportada.value = false
  error.value = `Camara no disponible: ${err.message}. Usa busqueda manual.`
}

async function procesarToken(token: string) {
  if (cargando.value) return
  cargando.value = true
  error.value = ''
  try {
    const data = await api.verificarQr(token) as {
      valido: boolean
      usuario?: UsuarioVerificado
      resumen?: ResumenVacuna[]
    }
    if (!data.valido || !data.usuario) {
      throw new Error('Token invalido o expirado.')
    }
    tokenPaciente.value = token
    pacienteCurp.value = data.usuario.curp
    paciente.value = data.usuario
    resumen.value = data.resumen || []
    cameraEnabled.value = false
    fase.value = 'paciente'
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'No se pudo verificar el codigo.'
  } finally {
    cargando.value = false
  }
}

async function buscarPorCurp() {
  if (pacienteCurp.value.length !== 18) {
    error.value = 'La CURP debe tener 18 caracteres.'
    return
  }
  cargando.value = true
  error.value = ''
  try {
    // Generamos un token temporal para el paciente, luego lo validamos.
    const r = await api.getQrToken(pacienteCurp.value.toUpperCase())
    await procesarToken(r.token)
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'No se encontro el paciente.'
  } finally {
    cargando.value = false
  }
}

function abrirRegistro(vacunaId: number) {
  const v = catalogo.value.find(c => c.id === vacunaId)
  const r = resumen.value.find(x => x.vacuna_id === vacunaId)
  form.vacuna_id = vacunaId
  form.numero_dosis = r ? Math.min((r.dosis_aplicadas || 0) + 1, v?.dosis_total || 1) : 1
  form.lugar_aplicacion = ''
  form.lote = ''
  error.value = ''
  fase.value = 'registrar'
}

async function aplicarDosis() {
  error.value = ''
  if (!form.vacuna_id) {
    error.value = 'Selecciona una vacuna.'
    return
  }
  if (form.numero_dosis < 1) {
    error.value = 'El numero de dosis debe ser al menos 1.'
    return
  }
  cargando.value = true
  try {
    const hoy = new Date().toISOString().slice(0, 10)
    await api.aplicarDosisPorQr({
      token:             tokenPaciente.value,
      vacuna_id:         form.vacuna_id,
      numero_dosis:      form.numero_dosis,
      fecha_aplicacion:  hoy,
      lugar_aplicacion:  form.lugar_aplicacion.trim() || undefined,
      lote:              form.lote.trim() || undefined,
      actor_curp:        curpMedico.value,
    })
    const vac = catalogo.value.find(c => c.id === form.vacuna_id)
    ultimaDosisAplicada.value = {
      vacuna: vac?.nombre || 'Vacuna',
      numero: form.numero_dosis,
    }
    fase.value = 'exito'
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'No se pudo registrar la dosis.'
  } finally {
    cargando.value = false
  }
}

function nuevoPaciente() {
  tokenPaciente.value = ''
  pacienteCurp.value = ''
  paciente.value = null
  resumen.value = []
  ultimaDosisAplicada.value = null
  error.value = ''
  cameraEnabled.value = true
  fase.value = 'scan'
}

function volverAPaciente() {
  fase.value = 'paciente'
  error.value = ''
}

const sumario = computed(() => {
  if (!resumen.value.length) return null
  const completas = resumen.value.filter(r => r.completa).length
  const pendientes = resumen.value.length - completas
  return { completas, pendientes, total: resumen.value.length }
})
</script>

<template>
  <div class="min-h-screen" style="background: var(--paper)">

    <!-- Header -->
    <header class="border-b" style="border-color: var(--ink)">
      <div class="max-w-5xl mx-auto px-6 lg:px-10 py-5 flex items-center justify-between gap-4">
        <div>
          <p class="eyebrow" style="color: var(--muted)">Panel medico</p>
          <h1 class="font-display text-2xl lg:text-3xl mt-0.5" style="font-weight: 500">
            Registro de dosis
          </h1>
        </div>
        <div class="text-right">
          <p class="font-mono text-[11px] uppercase" style="color: var(--muted); letter-spacing: 0.1em">
            {{ nombreMedico || 'Medico' }}
          </p>
          <button type="button" class="text-xs mt-1 underline-offset-2 hover:underline" style="color: var(--muted)" @click="logout">
            Cerrar sesion ↗
          </button>
        </div>
      </div>
    </header>

    <main class="max-w-5xl mx-auto px-6 lg:px-10 py-8 lg:py-12 space-y-8">

      <!-- FASE 1: SCAN -->
      <section v-if="fase === 'scan'" class="grid grid-cols-1 lg:grid-cols-[1.4fr_1fr] gap-8">
        <div>
          <p class="eyebrow" style="color: var(--muted)">Paso 1</p>
          <h2 class="font-display text-3xl lg:text-4xl mt-2" style="font-weight: 500">
            Escanea el <em class="italic" style="font-weight: 300">QR del paciente.</em>
          </h2>
          <p class="text-sm mt-3" style="color: var(--muted); max-width: 460px">
            Pidele al ciudadano que abra su cartilla digital y muestre su codigo QR personal.
            Tambien puedes registrar la CURP manualmente si no esta disponible.
          </p>

          <div class="mt-6 border-2 overflow-hidden bg-black aspect-[4/3] relative" style="border-color: var(--ink)">
            <QrcodeStream
              v-if="cameraSoportada && cameraEnabled"
              @detect="onScan"
              @error="onCameraError"
            />
            <div v-else class="w-full h-full flex flex-col items-center justify-center p-6 text-center" style="background: var(--moss-dark); color: var(--paper)">
              <p class="eyebrow" style="opacity: 0.7">Sin camara</p>
              <p class="mt-2 text-sm" style="opacity: 0.85">
                No se pudo iniciar la camara. Usa la busqueda manual.
              </p>
            </div>
          </div>

          <button type="button" class="btn-ghost mt-4 text-sm" @click="fase = 'manual'">
            Buscar por CURP manualmente →
          </button>

          <div v-if="error" class="mt-4 flex items-start gap-2 px-3 py-2.5 border-l-2" style="border-color: var(--wine); background: rgba(153,27,27,0.04)">
            <p class="text-[13px]" style="color: var(--wine)">{{ error }}</p>
          </div>
        </div>

        <aside class="border p-6" style="border-color: var(--border); background: white">
          <p class="eyebrow" style="color: var(--muted)">Por que QR</p>
          <h3 class="font-display text-xl mt-2" style="font-weight: 500">
            Identificacion oficial
          </h3>
          <ul class="mt-4 space-y-3 text-sm" style="color: var(--ink2)">
            <li class="flex gap-3">
              <span class="font-mono text-xs" style="color: var(--moss)">01</span>
              <span>Cada paciente tiene un token unico que expira en minutos.</span>
            </li>
            <li class="flex gap-3">
              <span class="font-mono text-xs" style="color: var(--moss)">02</span>
              <span>La dosis queda firmada con tu CURP, hora y unidad asignada.</span>
            </li>
            <li class="flex gap-3">
              <span class="font-mono text-xs" style="color: var(--moss)">03</span>
              <span>El ciudadano ve la dosis en su cartilla en tiempo real.</span>
            </li>
          </ul>
        </aside>
      </section>

      <!-- FASE 2: MANUAL -->
      <section v-else-if="fase === 'manual'" class="max-w-md">
        <p class="eyebrow" style="color: var(--muted)">Busqueda manual</p>
        <h2 class="font-display text-3xl mt-2" style="font-weight: 500">
          CURP del paciente
        </h2>
        <p class="text-sm mt-3" style="color: var(--muted)">
          Si el QR no esta disponible, ingresa la CURP de 18 caracteres.
        </p>

        <input
          v-model="pacienteCurp"
          maxlength="18"
          class="field mono mt-5 uppercase tracking-wider"
          placeholder="XXXX000000XXXXXXXX"
          autocomplete="off"
          @input="pacienteCurp = pacienteCurp.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 18)"
          @keyup.enter="buscarPorCurp"
        />

        <div v-if="error" class="mt-4 flex items-start gap-2 px-3 py-2.5 border-l-2" style="border-color: var(--wine); background: rgba(153,27,27,0.04)">
          <p class="text-[13px]" style="color: var(--wine)">{{ error }}</p>
        </div>

        <div class="mt-5 flex gap-3">
          <button type="button" class="btn-primary flex-1" :disabled="cargando" @click="buscarPorCurp">
            <span>{{ cargando ? 'Buscando…' : 'Continuar' }}</span>
            <span class="font-mono text-sm ml-2">→</span>
          </button>
          <button type="button" class="btn-ghost" @click="fase = 'scan'; error = ''">
            Volver al QR
          </button>
        </div>
      </section>

      <!-- FASE 3: PACIENTE -->
      <section v-else-if="fase === 'paciente' && paciente">
        <div class="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <p class="eyebrow" style="color: var(--muted)">Paciente identificado</p>
            <h2 class="font-display text-3xl lg:text-4xl mt-2" style="font-weight: 500">
              {{ paciente.nombre }} {{ paciente.apellido_paterno }}
              <span v-if="paciente.apellido_materno"> {{ paciente.apellido_materno }}</span>
            </h2>
            <p class="font-mono text-xs mt-2" style="color: var(--muted); letter-spacing: 0.12em">
              {{ paciente.curp }}
            </p>
            <p v-if="paciente.unidad_nombre" class="text-sm mt-1" style="color: var(--muted)">
              {{ paciente.unidad_nombre }}
            </p>
          </div>
          <button type="button" class="btn-ghost text-xs" @click="nuevoPaciente">
            Cambiar paciente ↗
          </button>
        </div>

        <div v-if="sumario" class="mt-6 grid grid-cols-3 gap-6 max-w-md">
          <div>
            <p class="tabular font-display text-3xl" style="font-weight: 400">{{ sumario.completas }}</p>
            <p class="eyebrow mt-1" style="color: var(--muted)">Completas</p>
          </div>
          <div>
            <p class="tabular font-display text-3xl" :style="`color: ${sumario.pendientes > 0 ? 'var(--wine)' : 'var(--ink)'}; font-weight: 400`">
              {{ sumario.pendientes }}
            </p>
            <p class="eyebrow mt-1" style="color: var(--muted)">Pendientes</p>
          </div>
          <div>
            <p class="tabular font-display text-3xl" style="font-weight: 400">{{ sumario.total }}</p>
            <p class="eyebrow mt-1" style="color: var(--muted)">Vacunas</p>
          </div>
        </div>

        <div class="mt-10">
          <div class="border-b pb-2 mb-4 flex items-baseline justify-between gap-3" style="border-color: var(--ink)">
            <h3 class="font-display text-2xl" style="font-weight: 500">Aplicar dosis</h3>
            <p class="eyebrow" style="color: var(--muted)">Elige la vacuna</p>
          </div>

          <div v-if="resumen.length === 0" class="py-8 text-center">
            <p class="font-display text-lg italic" style="color: var(--muted); font-weight: 300">
              No hay vacunas registradas en su esquema todavia.
            </p>
            <button type="button" class="btn-primary mt-4" @click="abrirRegistro(catalogo[0]?.id || 0)">
              Registrar primera dosis →
            </button>
          </div>

          <div v-else class="divide-y" style="border-color: var(--border)">
            <button
              v-for="r in resumen"
              :key="r.vacuna_id"
              type="button"
              :disabled="r.completa"
              class="w-full text-left py-4 flex items-center justify-between gap-4 group transition-colors"
              :class="r.completa ? 'opacity-50 cursor-not-allowed' : 'hover:bg-[rgba(14,80,55,0.04)]'"
              style="border-color: var(--border)"
              @click="!r.completa && abrirRegistro(r.vacuna_id)"
            >
              <div class="flex-1 min-w-0">
                <p style="font-weight: 500">{{ r.nombre }}</p>
                <p class="text-xs mt-0.5" style="color: var(--muted)">
                  {{ r.dosis_aplicadas }} de {{ r.dosis_total }} dosis
                </p>
              </div>
              <span v-if="r.completa" class="font-mono text-[10px] uppercase" style="color: var(--moss); letter-spacing: 0.08em">
                completa
              </span>
              <span v-else class="font-mono text-sm" style="color: var(--moss)">
                + dosis {{ Math.min(r.dosis_aplicadas + 1, r.dosis_total) }} →
              </span>
            </button>
          </div>
        </div>

        <div v-if="error" class="mt-4 flex items-start gap-2 px-3 py-2.5 border-l-2" style="border-color: var(--wine); background: rgba(153,27,27,0.04)">
          <p class="text-[13px]" style="color: var(--wine)">{{ error }}</p>
        </div>
      </section>

      <!-- FASE 4: REGISTRAR -->
      <section v-else-if="fase === 'registrar' && paciente" class="max-w-xl">
        <p class="eyebrow" style="color: var(--muted)">Registrar dosis</p>
        <h2 class="font-display text-3xl mt-2" style="font-weight: 500">
          {{ catalogo.find(c => c.id === form.vacuna_id)?.nombre }}
        </h2>
        <p class="text-sm mt-2" style="color: var(--muted)">
          Paciente: <span class="font-mono text-xs" style="letter-spacing: 0.12em">{{ paciente.curp }}</span> ·
          {{ paciente.nombre }} {{ paciente.apellido_paterno }}
        </p>

        <div class="mt-6 space-y-5">
          <label class="block">
            <span class="eyebrow">Numero de dosis</span>
            <input v-model.number="form.numero_dosis" type="number" min="1" max="20" class="field mt-2 max-w-[140px]" />
          </label>

          <label class="block">
            <span class="eyebrow">Lugar de aplicacion</span>
            <input v-model="form.lugar_aplicacion" type="text" class="field mt-2" placeholder="UMF, hospital o sitio de campania" maxlength="200" />
          </label>

          <label class="block">
            <span class="eyebrow">Lote (opcional)</span>
            <input v-model="form.lote" type="text" class="field mt-2 mono" placeholder="LOT-XXX-000" maxlength="60" />
          </label>

          <div class="border-t pt-4 text-xs font-mono" style="border-color: var(--border); color: var(--muted); letter-spacing: 0.06em">
            FECHA · {{ new Date().toLocaleDateString('es-MX') }}<br />
            HORA · {{ new Date().toLocaleTimeString('es-MX') }}<br />
            FIRMADO POR · {{ curpMedico }}
          </div>

          <div v-if="error" class="flex items-start gap-2 px-3 py-2.5 border-l-2" style="border-color: var(--wine); background: rgba(153,27,27,0.04)">
            <p class="text-[13px]" style="color: var(--wine)">{{ error }}</p>
          </div>

          <div class="flex gap-3 pt-2">
            <button type="button" class="btn-primary flex-1" :disabled="cargando" @click="aplicarDosis">
              <span>{{ cargando ? 'Registrando…' : 'Aplicar dosis' }}</span>
              <span class="font-mono text-sm ml-2">→</span>
            </button>
            <button type="button" class="btn-ghost" @click="volverAPaciente">
              Cancelar
            </button>
          </div>
        </div>
      </section>

      <!-- FASE 5: EXITO -->
      <section v-else-if="fase === 'exito' && paciente && ultimaDosisAplicada" class="max-w-xl">
        <div class="border-l-4 pl-6 py-4" style="border-color: var(--moss)">
          <p class="eyebrow" style="color: var(--moss)">Dosis registrada</p>
          <h2 class="font-display text-3xl mt-2" style="font-weight: 500">
            {{ ultimaDosisAplicada.vacuna }}
            <span class="italic" style="font-weight: 300">dosis {{ ultimaDosisAplicada.numero }}.</span>
          </h2>
          <p class="text-sm mt-3" style="color: var(--muted)">
            La dosis quedo registrada en la cartilla de
            <span style="color: var(--ink); font-weight: 500">{{ paciente.nombre }} {{ paciente.apellido_paterno }}</span>
            con fecha y hora de hoy.
          </p>
        </div>

        <div class="mt-8 flex gap-3 flex-wrap">
          <button type="button" class="btn-primary" @click="volverAPaciente">
            Aplicar otra dosis al mismo paciente →
          </button>
          <button type="button" class="btn-ghost" @click="nuevoPaciente">
            Nuevo paciente
          </button>
        </div>
      </section>

    </main>
  </div>
</template>

<style scoped>
.field.mono {
  font-family: var(--font-mono);
}
</style>
