// mobile/app/mensajes.tsx
/**
 * Screen Mensajes (buzon completo).
 */
import { DashboardShell } from '@/components/domain/dashboard/DashboardShell'
import { HeroExpediente } from '@/components/domain/dashboard/HeroExpediente'
import { MensajesList } from '@/components/domain/dashboard/MensajesList'
import { useDashboardData } from '@/hooks/useDashboardData'

export default function MensajesScreen() {
  const { usuario, curp, mensajes } = useDashboardData()

  return (
    <DashboardShell>
      <HeroExpediente
        usuario={usuario}
        curp={curp}
        eyebrow="Buzon"
        titulo="Mensajes y"
        tituloItalic="avisos."
      />
      <MensajesList mensajes={mensajes} />
    </DashboardShell>
  )
}

// frontend/app/pages/mensajes.vue
<script setup lang="ts">
definePageMeta({ middleware: 'ciudadano' })
useHead({ title: 'Buzon de mensajes' })

const { t } = useI18n()
const {
  curp,
  resumen,
  usuario,
  mensajes,
  eliminarMensajeLocal,
  marcarLeidoLocal,
} = useDashboardData()
</script>

<template>
  <DashboardShell>
    <HeroExpediente
      :usuario="usuario"
      :curp="curp"
      :has-resumen="resumen.length > 0"
      :titulo="t('mensajes.title')"
      :titulo-italic="t('mensajes.titleItalic')"
      :eyebrow="t('mensajes.eyebrow')"
    />

    <MensajesList
      :mensajes="mensajes"
      @eliminar="eliminarMensajeLocal"
      @marcar-leido="marcarLeidoLocal"
    />
  </DashboardShell>
</template>
