// frontend/app/pages/aefi.vue
<script setup lang="ts">
definePageMeta({ middleware: 'ciudadano' })
useHead({ title: 'Eventos adversos (AEFI)' })

const { t } = useI18n()
const {
  curp,
  resumen,
  usuario,
  historialDetalle,
} = useDashboardData()
</script>

<template>
  <DashboardShell>
    <HeroExpediente
      :usuario="usuario"
      :curp="curp"
      :has-resumen="resumen.length > 0"
      :titulo="t('aefi.title')"
      :titulo-italic="t('aefi.titleItalic')"
      :eyebrow="t('aefi.eyebrow')"
    />

    <AefiSection :curp="curp" :historial="historialDetalle" />
  </DashboardShell>
</template>

// mobile/app/aefi.tsx
/**
 * Screen Eventos adversos (AEFI).
 */
import { DashboardShell } from '@/components/domain/dashboard/DashboardShell'
import { HeroExpediente } from '@/components/domain/dashboard/HeroExpediente'
import { AefiSection } from '@/components/domain/AefiSection'
import { useDashboardData } from '@/hooks/useDashboardData'

export default function AefiScreen() {
  const { usuario, curp } = useDashboardData()

  return (
    <DashboardShell>
      <HeroExpediente
        usuario={usuario}
        curp={curp}
        eyebrow="Farmacovigilancia"
        titulo="Eventos"
        tituloItalic="adversos."
      />
      {curp ? <AefiSection curp={curp} /> : null}
    </DashboardShell>
  )
}
