// frontend/app/pages/alergias.vue
<script setup lang="ts">
definePageMeta({ middleware: 'ciudadano' })
useHead({ title: 'Alergias y contraindicaciones' })

const { t } = useI18n()
const {
  curp,
  resumen,
  usuario,
  isAuthed,
} = useDashboardData()
</script>

<template>
  <DashboardShell>
    <HeroExpediente
      :usuario="usuario"
      :curp="curp"
      :has-resumen="resumen.length > 0"
      :titulo="t('alergias.title')"
      :titulo-italic="t('alergias.titleItalic')"
      :eyebrow="t('alergias.eyebrow')"
    />

    <AlergiasSection :curp="curp" :editable="isAuthed()" />
  </DashboardShell>
</template>

// mobile/app/alergias.tsx
/**
 * Screen Alergias y contraindicaciones.
 */
import { DashboardShell } from '@/components/domain/dashboard/DashboardShell'
import { HeroExpediente } from '@/components/domain/dashboard/HeroExpediente'
import { AlergiasSection } from '@/components/domain/AlergiasSection'
import { useDashboardData } from '@/hooks/useDashboardData'

export default function AlergiasScreen() {
  const { usuario, curp } = useDashboardData()

  return (
    <DashboardShell>
      <HeroExpediente
        usuario={usuario}
        curp={curp}
        eyebrow="Cuidados"
        titulo="Alergias y"
        tituloItalic="reacciones."
      />
      {curp ? <AlergiasSection curp={curp} editable /> : null}
    </DashboardShell>
  )
}
