// frontend/app/pages/unidad-medica.vue
<script setup lang="ts">
definePageMeta({ middleware: 'ciudadano' })
useHead({ title: 'Mi unidad medica' })

const { t } = useI18n()
const {
  curp,
  resumen,
  usuario,
} = useDashboardData()
</script>

<template>
  <DashboardShell>
    <HeroExpediente
      :usuario="usuario"
      :curp="curp"
      :has-resumen="resumen.length > 0"
      :titulo="t('unidadMedica.title')"
      :titulo-italic="t('unidadMedica.titleItalic')"
      :eyebrow="t('unidadMedica.eyebrow')"
    />

    <UnidadMedicaCard :usuario="usuario" />
  </DashboardShell>
</template>

// mobile/app/unidad-medica.tsx
/**
 * Screen Unidad medica (UMF y datos clinicos administrativos).
 */
import { DashboardShell } from '@/components/domain/dashboard/DashboardShell'
import { HeroExpediente } from '@/components/domain/dashboard/HeroExpediente'
import { UnidadMedicaCard } from '@/components/domain/dashboard/UnidadMedicaCard'
import { useDashboardData } from '@/hooks/useDashboardData'

export default function UnidadMedicaScreen() {
  const { usuario, curp } = useDashboardData()

  return (
    <DashboardShell>
      <HeroExpediente
        usuario={usuario}
        curp={curp}
        eyebrow="Mi unidad"
        titulo="Unidad"
        tituloItalic="medica."
      />
      <UnidadMedicaCard usuario={usuario} />
    </DashboardShell>
  )
}
