// frontend/app/components/domain/GrupoBadge.vue
<script setup lang="ts">
import { etiquetaGrupo } from '~/constants/grupos'
import type { GrupoPrioritario } from '~/types'

defineProps<{
  grupo: GrupoPrioritario | string | null | undefined
  small?: boolean
}>()
</script>

<template>
  <span
    v-if="grupo && grupo !== 'ninguno'"
    class="inline-flex items-center font-mono uppercase tracking-wider"
    :class="small ? 'text-[9px] px-1.5 py-0.5' : 'text-[10px] px-2 py-0.5'"
    style="background: var(--moss-soft); color: var(--moss-dark); letter-spacing: 0.1em"
  >
    {{ etiquetaGrupo(grupo) }}
  </span>
</template>

// mobile/src/components/domain/GrupoBadge.tsx
import { View } from 'react-native'
import { colors, spacing, typography } from '@/theme'
import { Text } from '@/components/ui/Text'
import { etiquetaGrupo } from '@/constants/grupos'
import type { GrupoPrioritario } from '@/types'

interface Props {
  grupo: GrupoPrioritario | string | null | undefined
}

export function GrupoBadge({ grupo }: Props) {
  if (!grupo || grupo === 'ninguno') return null
  return (
    <View
      style={{
        backgroundColor: colors.mossSoft,
        paddingHorizontal: spacing.sm,
        paddingVertical: 2,
        alignSelf: 'flex-start',
      }}
    >
      <Text
        style={{
          fontFamily: typography.mono,
          fontSize: 10,
          letterSpacing: 1.2,
          textTransform: 'uppercase',
          color: colors.mossDark,
        }}
      >
        {etiquetaGrupo(grupo)}
      </Text>
    </View>
  )
}
