// mobile/src/components/domain/DependientesSection.tsx
/**
 * Seccion editorial de dependientes / cuidadores en mobile.
 * Permite listar, agregar y eliminar dependientes vinculados.
 */
import { useCallback, useEffect, useState } from 'react'
import { Pressable, View } from 'react-native'

import { Text } from '@/components/ui/Text'
import { Field } from '@/components/ui/Field'
import { Button } from '@/components/ui/Button'
import { Modal } from '@/components/ui/Modal'
import { Skeleton } from '@/components/ui/Skeleton'
import { ChipSelector } from '@/components/ui/ChipSelector'
import { useToast } from '@/components/ui/Toast'
import { MiQrModal } from '@/components/domain/MiQrModal'
import { cuidadoresApi, type Dependiente } from '@/api/cuidadores'
import { colors, spacing } from '@/theme'

interface Props {
  curp: string
}

const GRUPO_LABEL: Record<string, string> = {
  adulto_mayor:    'Adulto mayor',
  embarazada:      'Embarazada',
  personal_salud:  'Personal de salud',
  cronico:         'Cronico',
}

const RELACIONES_COMUNES = [
  'Madre', 'Padre',
  'Hijo', 'Hija',
  'Esposo', 'Esposa',
  'Hermano', 'Hermana',
  'Abuelo', 'Abuela',
  'Nieto', 'Nieta',
  'Tio', 'Tia',
] as const

export function DependientesSection({ curp }: Props) {
  const toast = useToast()
  const [items, setItems] = useState<Dependiente[]>([])
  const [cargando, setCargando] = useState(true)

  const [showAgregar, setShowAgregar] = useState(false)
  const [showEliminar, setShowEliminar] = useState<Dependiente | null>(null)
  const [qrDep, setQrDep] = useState<Dependiente | null>(null)

  const [form, setForm] = useState({ curp_dependiente: '', relacion: '' })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  const recargar = useCallback(async () => {
    setCargando(true)
    try {
      const data = await cuidadoresApi.listar(curp)
      setItems(data)
    } catch {
      // silencioso
    } finally {
      setCargando(false)
    }
  }, [curp])

  useEffect(() => { recargar() }, [recargar])

  async function guardar() {
    setError('')
    const c = form.curp_dependiente.trim().toUpperCase()
    const r = form.relacion.trim()
    if (c.length !== 18) {
      setError('CURP invalida (18 caracteres).')
      return
    }
    if (!r) {
      setError('Indica la relacion.')
      return
    }
    setBusy(true)
    try {
      await cuidadoresApi.agregar({
        curp_cuidador: curp,
        curp_dependiente: c,
        relacion: r,
      })
      setShowAgregar(false)
      setForm({ curp_dependiente: '', relacion: '' })
      await recargar()
      toast.success('Dependiente vinculado.')
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'No se pudo agregar.'
      setError(msg)
      toast.error(msg)
    } finally {
      setBusy(false)
    }
  }

  async function confirmarEliminar() {
    if (!showEliminar) return
    try {
      await cuidadoresApi.eliminar(showEliminar.id)
      setShowEliminar(null)
      await recargar()
      toast.success('Relacion eliminada.')
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'No se pudo eliminar.')
      setShowEliminar(null)
    }
  }

  return (
    <View style={{ marginTop: spacing.lg }}>
      <View
        style={{
          flexDirection: 'row',
          alignItems: 'flex-end',
          justifyContent: 'space-between',
          borderBottomWidth: 1,
          borderBottomColor: colors.ink,
          paddingBottom: spacing.sm,
          marginBottom: spacing.md,
        }}
      >
        <Text variant="h2">A mi cargo</Text>
        <Pressable onPress={() => setShowAgregar(true)} hitSlop={6}>
          <Text variant="eyebrow">+ Dependiente</Text>
        </Pressable>
      </View>

      <Text variant="small" color="muted" style={{ marginBottom: spacing.md }}>
        Gestiona la cartilla de familiares a tu cuidado (adultos mayores, ninos, dependientes).
      </Text>

      {cargando ? (
        <View style={{ gap: spacing.sm, paddingVertical: spacing.md }}>
          <Skeleton width="60%" />
          <Skeleton width="40%" height={10} />
        </View>
      ) : !items.length ? (
        <View style={{ paddingVertical: spacing.xl, alignItems: 'center' }}>
          <Text variant="h3" italic color="muted" style={{ textAlign: 'center' }}>
            Aun no tienes dependientes vinculados.
          </Text>
        </View>
      ) : (
        <View>
          {items.map((d, i) => (
            <View
              key={d.id}
              style={{
                paddingVertical: spacing.md,
                borderBottomWidth: i < items.length - 1 ? 1 : 0,
                borderBottomColor: colors.borderSoft,
                flexDirection: 'row',
                gap: spacing.md,
              }}
            >
              <View style={{ flex: 1 }}>
                <Text variant="body" bold>
                  {d.nombre} {d.apellido_paterno} {d.apellido_materno ?? ''}
                </Text>
                <Text variant="mono" color="muted" style={{ fontSize: 10, letterSpacing: 1, marginTop: 2 }}>
                  {d.curp}
                </Text>
                <Text variant="small" color="muted" style={{ marginTop: 4 }}>
                  Relacion: {d.relacion}
                  {d.grupo_prioritario && d.grupo_prioritario !== 'ninguno'
                    ? ` · ${GRUPO_LABEL[d.grupo_prioritario] ?? d.grupo_prioritario}`
                    : ''}
                </Text>
              </View>
              <View style={{ gap: spacing.sm, alignItems: 'flex-end' }}>
                <Pressable
                  onPress={() => setQrDep(d)}
                  hitSlop={6}
                  accessibilityRole="button"
                  accessibilityLabel={`Ver QR de ${d.nombre}`}
                >
                  <Text variant="mono" color="moss" style={{ fontSize: 10, letterSpacing: 1 }}>
                    VER QR
                  </Text>
                </Pressable>
                <Pressable
                  onPress={() => setShowEliminar(d)}
                  hitSlop={6}
                >
                  <Text variant="mono" color="wine" style={{ fontSize: 10, letterSpacing: 1 }}>
                    ELIMINAR
                  </Text>
                </Pressable>
              </View>
            </View>
          ))}
        </View>
      )}

      <Modal
        visible={showAgregar}
        onClose={() => { setShowAgregar(false); setError('') }}
        eyebrow="Cartilla"
        title="Vincular dependiente"
      >
        <Field
          label="CURP del dependiente"
          value={form.curp_dependiente}
          onChangeText={(t) => setForm({ ...form, curp_dependiente: t.toUpperCase() })}
          placeholder="18 caracteres"
          autoCapitalize="characters"
          maxLength={18}
          mono
        />
        <ChipSelector
          label="Relacion"
          options={RELACIONES_COMUNES}
          value={form.relacion}
          onChange={(v) => setForm({ ...form, relacion: v })}
          allowCustom
          customLabel="Otra..."
          customPlaceholder="Especifica la relacion"
        />
        {error ? (
          <View
            style={{
              borderLeftWidth: 2,
              borderLeftColor: colors.wine,
              paddingLeft: spacing.md,
              paddingVertical: spacing.sm,
            }}
          >
            <Text variant="small" color="wine">{error}</Text>
          </View>
        ) : null}
        <Button
          label={busy ? 'Guardando...' : 'Vincular'}
          loading={busy}
          onPress={guardar}
          arrow={!busy}
        />
      </Modal>

      <Modal
        visible={!!showEliminar}
        onClose={() => setShowEliminar(null)}
        eyebrow="Confirmar"
        title="Eliminar relacion"
        maxWidth={420}
      >
        <Text variant="small" color="muted">
          Esto eliminara solo el vinculo de cuidado. La cartilla del dependiente no se borra.
        </Text>
        <View style={{ flexDirection: 'row', gap: spacing.sm }}>
          <View style={{ flex: 1 }}>
            <Button label="Cancelar" variant="ghost" onPress={() => setShowEliminar(null)} />
          </View>
          <View style={{ flex: 1 }}>
            <Pressable
              onPress={confirmarEliminar}
              style={{ backgroundColor: colors.wine, paddingVertical: spacing.md, alignItems: 'center' }}
              accessibilityRole="button"
            >
              <Text color="paper" bold>Eliminar</Text>
            </Pressable>
          </View>
        </View>
      </Modal>

      {qrDep ? (
        <MiQrModal
          visible={!!qrDep}
          onClose={() => setQrDep(null)}
          curp={qrDep.curp}
          titulo={`QR de ${qrDep.nombre} ${qrDep.apellido_paterno}`}
        />
      ) : null}
    </View>
  )
}

// frontend/app/components/domain/DependientesSection.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import Swal from 'sweetalert2'
import QrPersonalModal from '@/components/domain/QrPersonalModal.vue'

const props = defineProps<{
  curp: string
}>()

type Dependiente = {
  id: number
  curp: string
  nombre: string
  apellido_paterno: string
  apellido_materno: string | null
  grupo_prioritario: string
  relacion: string
  fecha_nacimiento: string | null
}

const items = ref<Dependiente[]>([])
const cargando = ref(true)
const qrDependiente = ref<Dependiente | null>(null)

async function recargar() {
  cargando.value = true
  try {
    items.value = await useApi().getDependientes(props.curp) as Dependiente[]
  } catch (e) {
    console.error(e)
  } finally {
    cargando.value = false
  }
}

async function agregar() {
  const { value: formValues } = await Swal.fire({
    title: 'Agregar dependiente',
    html: `
      <input id="dcurp" class="swal2-input" placeholder="CURP del dependiente" maxlength="18"/>
      <input id="rel" class="swal2-input" placeholder="Relacion (ej. madre, hijo, esposo)" />
    `,
    showCancelButton: true,
    confirmButtonColor: '#0E5037',
    cancelButtonColor: '#6B6A60',
    preConfirm: () => {
      const d = (document.getElementById('dcurp') as HTMLInputElement).value.trim().toUpperCase()
      const r = (document.getElementById('rel') as HTMLInputElement).value.trim()
      if (d.length !== 18) { Swal.showValidationMessage('CURP invalida'); return false }
      if (!r) { Swal.showValidationMessage('Indica la relacion'); return false }
      return { curp_dependiente: d, relacion: r }
    },
  })
  if (!formValues) return
  try {
    await useApi().agregarDependiente({ curp_cuidador: props.curp, ...formValues })
    await recargar()
  } catch (e: any) {
    await Swal.fire({ icon: 'error', title: 'Error', text: e.message, confirmButtonColor: '#0E5037' })
  }
}

async function eliminar(id: number) {
  const r = await Swal.fire({
    title: '¿Eliminar relacion?', icon: 'warning',
    showCancelButton: true, confirmButtonColor: '#991B1B',
    cancelButtonColor: '#6B6A60',
    confirmButtonText: 'Eliminar', cancelButtonText: 'Cancelar',
  })
  if (!r.isConfirmed) return
  await useApi().eliminarDependiente(id)
  await recargar()
}

const grupoLabel: Record<string, string> = {
  adulto_mayor: 'Adulto mayor',
  embarazada: 'Embarazada',
  personal_salud: 'Personal de salud',
  cronico: 'Cronico',
}

onMounted(recargar)
</script>

<template>
  <section class="mb-14">
    <div class="flex items-baseline justify-between border-b pb-2 mb-5" style="border-color: var(--ink)">
      <h2 class="font-display text-2xl" style="font-weight: 500">A mi cargo</h2>
      <button type="button" class="btn-ghost text-xs" @click="agregar">+ Dependiente</button>
    </div>

    <p class="text-sm mb-4" style="color: var(--muted)">
      Gestiona la cartilla de familiares a tu cuidado (adultos mayores, ninos, dependientes).
    </p>

    <div v-if="cargando" class="py-6 text-sm" style="color: var(--muted)">Cargando…</div>
    <div v-else-if="!items.length" class="py-8 text-center">
      <p class="font-display text-lg italic" style="color: var(--muted); font-weight: 300">
        Aun no tienes dependientes vinculados.
      </p>
    </div>
    <div v-else>
      <div v-for="(d, i) in items" :key="d.id"
           class="flex items-baseline justify-between gap-4 py-4"
           :style="i < items.length - 1 ? 'border-bottom: 1px dotted var(--border)' : ''">
        <div class="flex-1 min-w-0">
          <p style="font-weight: 500">{{ d.nombre }} {{ d.apellido_paterno }} {{ d.apellido_materno }}</p>
          <p class="text-xs mt-0.5" style="color: var(--muted)">
            <span class="font-mono uppercase tracking-wider">{{ d.relacion }}</span>
            <span v-if="grupoLabel[d.grupo_prioritario]"> · {{ grupoLabel[d.grupo_prioritario] }}</span>
            · CURP {{ d.curp }}
          </p>
        </div>
        <div class="flex flex-col items-end gap-1.5 text-xs"
             style="font-family: var(--font-mono); letter-spacing: 0.08em">
          <button type="button"
                  style="color: var(--moss)"
                  @click="qrDependiente = d">
            ver qr
          </button>
          <button type="button"
                  style="color: var(--wine)"
                  @click="eliminar(d.id)">
            desvincular
          </button>
        </div>
      </div>
    </div>

    <QrPersonalModal
      v-if="qrDependiente"
      :open="!!qrDependiente"
      :curp="qrDependiente.curp"
      :nombre="`${qrDependiente.nombre} ${qrDependiente.apellido_paterno}`"
      @close="qrDependiente = null"
    />
  </section>
</template>
